HOSTS:
  leap42:
    roles:
      - client
    platform: sles-12-x86_64
    box: M0ses/openSUSE-Leap-42.1-minimal
    hypervisor: vagrant
    repos:
      simp:
        url: https://dl.bintray.com/simp/4.2.0-Beta2
        gpgkeys:
          - https://raw.githubusercontent.com/NationalSecurityAgency/SIMP/master/GPGKEYS/RPM-GPG-KEY-SIMP
          - https://getfedora.org/static/0608B895.txt

CONFIG:
  log_level: verbose
  synced_folder : disabled
  type:      aio
  vagrant_memsize: 256
